package com.github.michaelboyles.simpledi.test;

import com.github.michaelboyles.simpledi.ISimpleDIContext;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class VehicleService {

    public void executeVehicle() {
        ISimpleDIContext simpleDIContext = new ExampleCopiedAutoGeneratedSimpleDIContext();
        Car car = (Car) simpleDIContext.getBeanByName("car");
        log.info("Car: {}", car);
    }
}
